name: "revision-project"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Snave55555
      POSTGRES_DB: movies
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: Snave55555
      DB_NAME: movies
    ports:
      - 3001:3001
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001/api
    ports:
      - 3000:3000
volumes:
  db_data: